<a href="https://colab.research.google.com/github/Itsritu/oibsip_2/blob/main/Cleaning_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name:** Cleaning Data

**Dataset Loading**

In [32]:
# Importing the drive module from the google.colab library
from google.colab import drive

# Mounting the Google Drive at the specified location '/content/drive'
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
# Importing neccessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [27]:
# Reading the data
df = pd.read_csv('/content/AB_NYC_2019.csv')

**Dataset first view**

In [28]:
# Looking at the top 5 rows of the data
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [29]:
# Looking at the bottom 5 rows of the data
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

**Count of rows and columns**

In [30]:
# Number of rows
rows = df.shape[0]
# Number of columns
column = df.shape[1]
print("Number of rows: ",rows)
print("Number of columns: ",column)

Number of rows:  48895
Number of columns:  16

**Viewing dataset columns**

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

# **1. Data Integrity :-**

In [ ]:
# Check data types
print("Data Types:")
print(df.dtypes)

Data Types:
id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [ ]:
# Check 'price' column for values greater than 0
invalid_prices = df[df['price'] <= 0]
if not invalid_prices.empty:
    print("Invalid prices found:")
    print(invalid_prices.to_string(index=False))

Invalid prices found:
      id                                               name   host_id    host_name neighbourhood_group      neighbourhood  latitude  longitude       room_type  price  minimum_nights  number_of_reviews last_review  reviews_per_month  calculated_host_listings_count  availability_365
18750597  Huge Brooklyn Brownstone Living, Close to it all.   8993084     Kimberly            Brooklyn Bedford-Stuyvesant  40.69023  -73.95428    Private room      0               4                  1  2018-01-06               0.05                               4                28
20333471      ★Hostel Style Room | Ideal Traveling Buddies★ 131697576       Anisha               Bronx    East Morrisania  40.83296  -73.88668    Private room      0               2                 55  2019-06-24               2.56                               4               127
20523843    MARTIAL LOFT 3: REDEMPTION (upstairs, 2nd room)  15787004 Martial Loft            Brooklyn           Bushwick  40.69467  -73.92433    Private room      0               2                 16  2019-05-18               0.71                               5                 0
20608117                    Sunny, Quiet Room in Greenpoint   1641537       Lauren            Brooklyn         Greenpoint  40.72462  -73.94072    Private room      0               2                 12  2017-10-27               0.53                               2                 0
20624541      Modern apartment in the heart of Williamsburg  10132166      Aymeric            Brooklyn       Williamsburg  40.70838  -73.94645 Entire home/apt      0               5                  3  2018-01-02               0.15                               1                73
20639628 Spacious comfortable master bedroom with nice view  86327101      Adeyemi            Brooklyn Bedford-Stuyvesant  40.68173  -73.91342    Private room      0               1                 93  2019-06-15               4.28                               6               176
20639792  Contemporary bedroom in brownstone with nice view  86327101      Adeyemi            Brooklyn Bedford-Stuyvesant  40.68279  -73.91170    Private room      0               1                 95  2019-06-21               4.37                               6               232
20639914       Cozy yet spacious private brownstone bedroom  86327101      Adeyemi            Brooklyn Bedford-Stuyvesant  40.68258  -73.91284    Private room      0               1                 95  2019-06-23               4.35                               6               222
20933849                              the best you can find  13709292       Qiuchi           Manhattan        Murray Hill  40.75091  -73.97597 Entire home/apt      0               3                  0         NaN                NaN                               1                 0
21291569  Coliving in Brooklyn! Modern design / Shared room 101970559       Sergii            Brooklyn           Bushwick  40.69211  -73.90670     Shared room      0              30                  2  2019-06-22               0.11                               6               333
21304320             Best Coliving space ever! Shared room. 101970559       Sergii            Brooklyn           Bushwick  40.69166  -73.90928     Shared room      0              30                  5  2019-05-24               0.26                               6               139

# **2. Missing Data Handling :-**

**Missing/null values**

In [31]:
# Looking for missing values
missing_values  = df.isnull().sum()
missing_values

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
# Imputing missing 'name' and 'host_id' values with 'Unknown'
df['name'] = df['name'].fillna('Unknown')
df['host_name'] = df['host_name'].fillna('Unknown')

# Imputing missing 'last_review' values with the most common date (mode)
common_last_review = df['last_review'].mode()[0]
df['last_review'].fillna(common_last_review, inplace=True)

#Imputing missing 'reviews_per_month' values with the mean
mean_reviews_per_month = df['reviews_per_month'].mean()
df['reviews_per_month'].fillna(mean_reviews_per_month, inplace=True)

# Print the number of missing values in each column after imputation
print("Number of missing values in each column:")
print(df.isnull().sum())

Number of missing values in each column:
id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

# **3. Duplicate Removal :-**

In [ ]:
# Finding duplicate values
duplicate_values_count = len(df[df.duplicated()])
print(f' The duplicates values in the dataset is  {duplicate_values_count}')

 The duplicates values in the dataset is  0

# **4. Standardization :-**

In [ ]:
# Selecting only the numerical columns for standardization
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [ ]:
# Standardizing the numerical columns using Z-score
scaler = StandardScaler()
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [ ]:
# Standardizing the numerical columns using Z-score
scaler = StandardScaler()
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,-1.731277,Clean & quiet apt home by the park,-0.860159,John,Brooklyn,Kensington,-1.493849,-0.437652,Private room,-0.015493,-0.293996,-0.320414,2018-10-19,-7.766410e-01,-0.034716,1.916250
1,-1.731272,Skylit Midtown Castle,-0.860158,Jennifer,Manhattan,Midtown,0.452436,-0.684639,Entire home/apt,0.300974,-0.293996,0.487665,2019-05-21,-6.631381e-01,-0.156104,1.840275
2,-1.731176,THE VILLAGE OF HARLEM....NEW YORK !,-0.860135,Elisabeth,Manhattan,Harlem,1.468399,0.222497,Private room,-0.011329,-0.196484,-0.522433,2019-06-23,-2.790146e-17,-0.186451,1.916250
3,-1.731159,Cozy Entire Floor of Brownstone,-0.860132,LisaRoxanne,Brooklyn,Clinton Hill,-0.803398,-0.164450,Entire home/apt,-0.265335,-0.293996,5.538156,2019-07-05,2.181110e+00,-0.186451,0.617065
4,-1.731051,Entire Apt: Spacious Studio/Loft by central park,-0.860103,Laura,Manhattan,East Harlem,1.275660,0.177216,Entire home/apt,-0.302811,0.144807,-0.320414,2018-11-19,-8.500840e-01,-0.186451,-0.856865

# **5. Outlier Detection :-**

In [ ]:
# Define the columns for outlier detection
columns_for_outlier_detection = ['latitude', 'longitude', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

# Calculate z-scores for the selected columns
z_scores = df[columns_for_outlier_detection].apply(lambda x: np.abs((x - x.mean()) / x.std()))

# Set a threshold for outlier detection
threshold = 3

# Identify outliers based on the threshold
outliers = df[z_scores > threshold]

# Address outliers and  Replace outliers with median values
median_values = df[columns_for_outlier_detection].median()
df[outliers.columns] = outliers.fillna(median_values)